services:
  - type: web
    name: telegram-product-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
    scaling:
      minInstances: 1
      maxInstances: 1
